set number
set cursorline
set cursorcolumn
set colorcolumn=80

set tabstop=2    
set expandtab    
set shiftwidth=2 
set smartindent  
set cindent     

set foldmethod=indent
nnoremap <space> za
vnoremap <space> zf
set cindent


autocmd BufNewFile  *.c     0r ~/.vim/template/skeleton.c
autocmd BufNewFile  *.sh    0r ~/.vim/template/skeleton.sh
autocmd BufNewFile  *.py    0r ~/.vim/template/skeleton.py
